#! /bin/bash
pushd ~ > /dev/null
md5sum --quiet -c ~/dotfiles/md5s | grep FAILED | sed -e 's/:.*//' -e 's/^\.//' |
        while read FILE; do
                echo copied $FILE;
		cp ~/.$FILE ~/dotfiles/$FILE;
	done
cat ~/dotfiles/md5s | awk '{print $2}' | 
	while read FILE; do
		md5sum $FILE >> ~/dotfiles/md5s.tmp
      echo md5 $FILE
	done
mv ~/dotfiles/md5s.tmp ~/dotfiles/md5s

