set nocompatible   " Disable vi-compatibility
syntax enable
set encoding=utf-8

set showcmd                     
filetype off


set nu " Enable line numbers, map Ctrl-N twice to toggle them
nmap <C-N><C-N> :set invnumber<CR>

" w!! to write out as root
" http://www.reddit.com/r/vim/comments/16w481/what_is_your_vimrc_and_why_do_you_like_it/
cmap w!! w !sudo tee % >/dev/null

set ruler " Show the cursor position
set tabstop=3 shiftwidth=3      
set ai 
set expandtab                   
set backspace=indent,eol,start  

" set list
" set listchars=
" set listchars+=tab:»\ 
" set listchars+=extends:› 
" set listchars+=precedes:‹ 
" set listchars+=nbsp:· 
" set listchars+=trail:·

" Paste Mode
nnoremap <F8> :set invpaste paste?<CR>
set pastetoggle=<F8>
set showmode

set hlsearch                    
set incsearch                   
set ignorecase                  
set smartcase                   

set mouse=a " enable mouse in all modes
set ttymouse=xterm  " set mouse type to xterm

" Vundle

" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
"
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'
" Bundles
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'tpope/vim-fugitive'
Bundle 'matschaffer/netrw-v142'
Bundle 'Lokaltog/vim-powerline' 
" https://github.com/Lokaltog/vim-powerline/wiki/Patched-fonts
Bundle 'nanotech/jellybeans.vim'
"requires vim 7.3
Bundle 'myusuf3/numbers.vim' 
nnoremap <F3> :NumbersToggle<CR>

filetype plugin indent on

" quit NERDTree after opening a file
let NERDTreeQuitOnOpen=1
" colored NERD Tree
let NERDChristmasTree = 1
let NERDTreeHighlightCursorline = 1
let NERDTreeShowHidden = 1
" map enter to activating a node
let NERDTreeMapActivateNode='<CR>'
let NERDTreeIgnore=['\.git','\.DS_Store','\.pdf', '.beam']

" Toggle NERDTree with <leader>d
map <silent> <leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>

" Powerline
set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show unicode glyphs
let g:Powerline_symbols = 'fancy'


" Jellybeans
colorscheme jellybeans
