set nocompatible   " Disable vi-compatibility
syntax enable
set encoding=utf-8

set showcmd                     
filetype off


set nu " Enable line numbers, map Ctrl-N twice to toggle them
nmap <C-N><C-N> :set invnumber<CR>

" w!! to write out as root
" http://www.reddit.com/r/vim/comments/16w481/what_is_your_vimrc_and_why_do_you_like_it/
cmap w!! w !sudo tee % >/dev/null

set ruler " Show the cursor position
set tabstop=2 shiftwidth=2      
set ai 
set expandtab                   
set backspace=indent,eol,start  

" set list
" set listchars=
" set listchars+=tab:»\ 
" set listchars+=extends:› 
" set listchars+=precedes:‹ 
" set listchars+=nbsp:· 
" set listchars+=trail:·

" Paste Mode
nnoremap <F8> :set invpaste paste?<CR>
set pastetoggle=<F8>
set showmode

set hlsearch                    
set incsearch                   
set ignorecase                  
set smartcase                   

set mouse=a " enable mouse in all modes
set ttymouse=xterm  " set mouse type to xterm

" Vundle

" git clone https://github.com/gmarik/vundle.git ~/.vim/bundle/vundle
"
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
Bundle 'gmarik/vundle'
" Bundles
Bundle 'scrooloose/nerdtree'
Bundle 'scrooloose/nerdcommenter'
Bundle 'tpope/vim-fugitive'
Bundle 'matschaffer/netrw-v142'
Bundle 'bling/vim-airline'
Bundle 'nanotech/jellybeans.vim'
Bundle 'airblade/vim-gitgutter'
"requires vim 7.3
Bundle 'myusuf3/numbers.vim' 
Bundle 'tpope/vim-markdown'
Bundle 'altercation/vim-colors-solarized'
Bundle 'ivyl/vim-bling'
"Bundle 'mileszs/ack.vim'
Bundle 'rking/ag.vim'
"Bundle 'xolox/vim-misc'
"Bundle 'xolox/vim-notes'
Bundle 'Valloric/YouCompleteMe'
Bundle 'scrooloose/syntastic'

filetype plugin indent on

" quit NERDTree after opening a file
let NERDTreeQuitOnOpen=1
" colored NERD Tree
let NERDChristmasTree = 1
let NERDTreeHighlightCursorline = 1
let NERDTreeShowHidden = 1
" map enter to activating a node
let NERDTreeMapActivateNode='<CR>'
let NERDTreeIgnore=['\.git','\.DS_Store','\.pdf', '.beam']

" Toggle NERDTree with <leader>d
map <silent> <leader>d :execute 'NERDTreeToggle ' . getcwd()<CR>

set laststatus=2   " Always show the statusline
set encoding=utf-8 " Necessary to show unicode glyphs

" Airline
let g:airline_powerline_fonts = 1

" Solarized
syntax enable
set background=dark
colorscheme solarized

" Numbers
nnoremap <F3> :NumbersToggle<CR>

" Notes
"let g:notes_directories = ['~/Documents/Notes']

" Shortcut to rapidly toggle `set list`
nmap <leader>l :set list!<CR>

" Use the same symbols as TextMate for tabstops and EOLs
set listchars=tab:▸\ ,eol:¬

" Use system clipboard
set clipboard=unnamed
