#! /usr/bin/env bash

if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

if [ -d /opt/homebrew ]; then
  eval "$(/opt/homebrew/bin/brew shellenv)"
fi

if which brew &> /dev/null; then
  [[ -r "$(brew --prefix)/etc/profile.d/bash_completion.sh" ]] && . "$(brew --prefix)/etc/profile.d/bash_completion.sh"

  if [ -d `brew --prefix`/etc/bash_completion.d ]; then
    for COMPLETIONFILE in `brew --prefix`/etc/bash_completion.d/*; do
      source $COMPLETIONFILE;
    done >/dev/null 2>&1
  fi
fi
