#! /usr/bin/env bash

if [ -f $CONFIGDIR/ack/ackrc ]; then
   export ACKRC=$CONFIGDIR/ack/ackrc
fi
if which ag &> /dev/null; then
   alias ack=ag
else 
   alias ag=ack
   if which ack-grep &> /dev/null; then
      alias ack=ack-grep
   fi
fi

