#! /usr/bin/env bash

#if [ -f ~/Documents/Projects/ansible/derf/ansible.cfg ]; then
#   export ANSIBLE_CONFIG=~/Documents/Projects/ansible/derf/ansible.cfg
#fi

# environment

# aliases

# functions

function ansible-playbook {
  `which ansible-playbook` $* $ANSIBLE_EXTRA_VARS
}



function setansibleenv {
  unset ANSIBLE_EXTRA_VARS;
  source ~/workspace/ansible-envs/$1.txt
  for FILE in $ANSIBLE_VAR_FILES; do
    if [[ -e "$FILE" ]]; then
      echo "including $FILE";
      export ANSIBLE_EXTRA_VARS="$ANSIBLE_EXTRA_VARS -e @$FILE";
    fi
  done
  echo "Ansible set to $1"
}
complete -W "$(ls ~/workspace/ansible-envs/*.txt  2> /dev/null | sed -e 's/.*\///' | cut -f 1 -d '.')" setansibleenv

export ANSIBLE_COW_SELECTION=random
#export ANSIBLE_NOCOWS=1
