#! /usr/bin/env bash

### Amazon Web Services

if [[ -f ~/.aws/config ]]; then

  #functions
  function setawsenv {
    export AWS_PROFILE="$1"
    export SETENV_NAME=$AWS_PROFILE
    echo "AWS set to $1"
  }
  complete -W "$(aws configure list-profiles)" setawsenv

fi

if which aws &> /dev/null; then
  if which aws_completer &> /dev/null; then
    complete -C aws_completer aws
  fi
fi
export AWS_REGION='us-east-1'
