#! /usr/bin/env bash

### Amazon Web Services

if [[ -f ~/.aws/config ]]; then

  #functions
  function setawsenv {
    export AWS_PROFILE="$1"
    aws iam list-account-aliases > /dev/null 2>&1 || aws sso login
    export SETENV_NAME=$(aws iam list-account-aliases | jq .AccountAliases[0] | sed -e 's/"//g')
    if [[ -z $SETENV_NAME ]] || [[ "$SETENV_NAME" == "null" ]]; then
      export SETENV_NAME=$AWS_PROFILE
    fi
    echo "AWS set to $1"
  }
  complete -W "$(aws configure list-profiles)" setawsenv
  export AWS_REGION="us-east-2"

  function setawsregion {
    export AWS_REGION="$1"
  }
  #complete -W "$(aws ec2 describe-regions | jq '.Regions[] | .RegionName' | sed -e 's/"//g')" setawsregion
  complete -W "us-east-1 us-east-2" setawsregion

  function makesshconfig {
    aws ec2 describe-instances | jq '.Reservations[].Instances[] | (.Tags[]|select(.Key=="Name")|.Value), .PrivateIpAddress' | while read HOSTNAME; do read IPADDRESS; echo "Host $HOSTNAME" | sed -e 's/"//g'; echo "    HostName $IPADDRESS" | sed -e 's/"//g'; done
  }

fi

if which aws &> /dev/null; then
  if which aws_completer &> /dev/null; then
    complete -C aws_completer aws
  fi
fi
export AWS_REGION='us-east-1'
