#! /usr/bin/env bash

## Pass

function bin-link () {
  current_location=$(/usr/bin/env pwd -P);
  if [ -z "$2" ]; then
    target_name=$1
  else
    target_name=$2
  fi
  ln -s $current_location/$1 $HOME/bin/$target_name
}

