#! /bin/bash

# Aliases
if [ -f /usr/bin/gnu/grep ]; then
	alias grep='/usr/bin/gnu/grep --color=auto'
else
	alias grep='grep --color=auto'
fi

alias mkdir='mkdir -p'

function http { (exec 3<>/dev/tcp/$1/$2; echo -e "$3 $4 HTTP/1.0\r\n\r\n" >&3; cat <&3); }
function portcheck { (exec 3<>/dev/tcp/$1/$2) &>/dev/null; OPEN=$?; [ $OPEN -eq 0 ] && echo "open" || echo "closed"; return $OPEN; }
function portscan { HOST=$1; STARTPORT=$(echo $2 | cut -f 1 -d '-'); ENDPORT=$(echo $2 | cut -f 2 -d '-'); for PORT in `seq $STARTPORT $ENDPORT`; do portcheck $HOST $PORT > /dev/null && echo $PORT; done }

function print { awk "{print \$$1}"; }

function linecount { wc -l; }

function sum { awk '{ sum+=$1 } END { print sum }'; }

function div { awk "BEGIN {print $1 / $2}"; }
function mult { awk "BEGIN {print $1 * $2}"; }
function subt { awk "BEGIN {print $1 - $2}"; }
function addit { awk "BEGIN {print $1 + $2}"; }


function timestamp { date +'%Y-%m-%d-%H%M'; }

function random { 
   COUNT=$#; 
   INDEX=$(expr $RANDOM % $COUNT); 
   (( INDEX+=1 )); 
   eval "echo \$$INDEX"; 
}

function singleline {
  COUNT=0;
   while read LINE; do
      if [[ "$COUNT" -gt "0" ]] ; then
         echo -n "$1";
      fi
      let COUNT=$COUNT+1;
      echo -n "$LINE";
   done
}
