#! /usr/bin/env bash


#DOCKER_MACHINE_IP="192.168.99.100"
#DOCKER_MACHINE_PORT="2376"

#if `portcheck $DOCKER_MACHINE_IP $DOCKER_MACHINE_PORT >&/dev/null`; then
#  export DOCKER_HOST=tcp://192.168.99.100:2376
#  export DOCKER_TLS_VERIFY=1
#  if [[ -d $HOME/.docker/machine/machines/default ]]; then
#    export DOCKER_CERT_PATH=$HOME/.docker/machine/machines/default
#  fi
#fi
