#! /bin/bash

function dshload {
   unset HOSTLIST; 
   INT=0; 
   if [ "$1" = "-" ]; then
      while read HOST; do
         echo "$HOST";
         HOSTLIST[$INT]=$HOST;
         INT=`expr $INT + 1`;
      done;
   else 
      for HOST in `cat $1 | awk '{if ($2) { printf($2) } else { printf($1) } print "\n" }' | sort | uniq`; do 
         HOSTLIST[$INT]=$HOST; 
         INT=`expr $INT + 1`; 
      done;
   fi

}
function dshlist { for HOST in ${HOSTLIST[*]}; do echo $HOST; done ;}
function dsh { HOSTMASK=$1; DATETIME=`date '+%D %T'`; shift 1; for HOST in `dshlist | grep $HOSTMASK`; do (ssh -o ConnectTimeout=5 -o StrictHostKeyChecking=no -x $HOST "$@" | xargs -n 500 echo $DATETIME $HOST: >> /tmp/dsh.log )& done; ACTIVE=1; until [[ $ACTIVE = 0 ]]; do jobs -l > /dev/null; ACTIVE=`jobs -p | wc -l`; printf "\r%s active jobs" $ACTIVE; done; }
