#! /bin/bash

function dshload {
   unset HOSTLIST; 
   INT=0; 
   if [ "$1" = "-" ]; then
      while read HOST; do
         echo "$HOST";
         HOSTLIST[$INT]=$HOST;
         INT=`expr $INT + 1`;
      done;
   else 
      for HOST in `cat $1 | awk '{if ($2) { printf($2) } else { printf($1) } print "\n" }' | sort | uniq`; do 
         HOSTLIST[$INT]=$HOST; 
         INT=`expr $INT + 1`; 
      done;
   fi

}
function dshlist { 
  cat ~/.ssh/config | grep "^Host" | sed -e 's/^Host //'
}

function dsh { 
  HOSTMASK=$1; 
  shift 1; 
  for HOST in `dshlist | grep $HOSTMASK`; do 
    (ssh -q -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -x $HOST "$@" | xargs -n 500 echo "$HOST:" | tee -a /tmp/dsh.log )&
  done; 
  ACTIVE=1; 
  until [[ $ACTIVE = 0 ]]; do 
    jobs -l > /dev/null; 
    ACTIVE=`jobs -p | wc -l`; 
    #printf "\r%s active jobs" $ACTIVE; 
  done; 
}

complete -W "$(cat ~/.ssh/config | grep "^Host" | sed -e 's/^Host //')" dsh
