#! /usr/bin/env bash

function dshlist { 
  cat ~/.ssh/config | grep "^Host" | sed -e 's/^Host //'
}

function dsh { 
  HOSTMASK=$1; 
  shift 1; 
  for HOST in `dshlist | grep $HOSTMASK`; do 
    (ssh -q -o ConnectTimeout=5 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -x $HOST "$@" | xargs -n 500 echo "$HOST:" | tee -a /tmp/dsh.log )&
  done; 
  ACTIVE=1; 
  until [[ $ACTIVE = 0 ]]; do 
    jobs -l > /dev/null; 
    ACTIVE=`jobs -p | wc -l`; 
    #printf "\r%s active jobs" $ACTIVE; 
  done; 
}

complete -W "$(cat ~/.ssh/config 2>/dev/null | grep "^Host" | sed -e 's/^Host //')" dsh
