#! /usr/bin/env bash

## Aliases

alias g=git

## Variables

export SRCPATH="$HOME/src/"

## Functions
#unalias gco

function gco {
  REPO=$1
  # Expand shorthand "owner/repo" to a GitHub SSH URL
  if [[ $REPO =~ ^[[:alnum:]_.-]+/[[:alnum:]_.-]+$ ]]; then
    REPO="git@github.com:$REPO.git"
  fi
  REPOPATH=$(echo $REPO | sed -e 's/.*@//' -e 's/:/\//' -e 's/.*\/\///' -e 's/.git$//' -e 's/\/[[:alnum:]_-]\+$//');
  REPONAME=$(echo $REPO | sed -e 's/.*\///' -e 's/.git$//');
  echo Cloning $REPONAME into $REPOPATH
  if ! [[ -d $SRCPATH$REPOPATH ]]; then
    mkdir -p $SRCPATH$REPOPATH;
  fi
  cd $SRCPATH$REPOPATH;
  if ! [[ -d $REPONAME ]]; then
    git clone $REPO $REPONAME;
  fi
  cd $REPONAME;
}
