#! /bin/bash

function gridssh { 
   HOST=$1; 
   SHORTHOST=$(echo $1 | sed -e 's/\.grid//');
   settitle $SHORTHOST
   shift;
   if [ $# -gt 0 ]; then
      ssh $HOST $@;
   else
      ssh -t $HOST "bash --rcfile /net/yum/admin/work/fred/.bashrc"; 
   fi
   settitle bash
}



function grid { HOST="grid-$1.grid"; shift; gridssh $HOST $@; }
function gpfs { HOST="gpfs$1.grid"; shift; gridssh $HOST $@; }
function ibm { HOST="ibm-$1.grid"; shift; gridssh $HOST $@; }
function dqa { HOST="dqa-$1.grid"; shift; gridssh $HOST $@; }
function uk { HOST="$1.uk.grid"; shift; gridssh $HOST $@; }
function snd { HOST="snd-$1.grid"; shift; gridssh $HOST $@; }
function nrg5 { HOST="nrg5-$1.nrg5.us.grid"; shift; gridssh $HOST $@; }
function nrg1 { HOST="nrg1-$1.nrg1.us.grid"; shift; gridssh $HOST $@; }
function infra { HOST="$1.infra.us.grid"; shift; gridssh $HOST $@; }
function hadoop1 { HOST="hadoop1-$1.grid"; shift; gridssh $HOST $@; }

function unv_lookup { grep $1 /net/yum/admin/vm_configs/master.latest; }
