#! /bin/bash

## History-db

# Variables

# don't put duplicate lines in the history. See bash(1) for more options
# ... or force ignoredups and ignorespace
export HISTCONTROL=ignoreboth
unset HISTFILESIZE
export HISTFILESIZE
unset HISTSIZE
export HISTSIZE
# append to the history file without overwriting, and write history out after every command execution
export HISTTIMEFORMAT='%Y-%m-%d %H:%M:%S - '
shopt -s histappend

#aliases

# functions

function post_history { 
   LAST_COMMAND=$(history 1 | sed -e 's/^ *[0-9]* *[0-9]*-[0-9]*-[0-9]* *[0-9]*:[0-9]*:[0-9]* *- *//g'); 
   curl -d hostname="$HOSTNAME" -d command="$LAST_COMMAND" http://derf.us/history/; 
} 

function get_history {  
   echo -n "enter password: "; 
   read -s HISTPASS; 
   history -c; 
   rm ~/.bash_history; 
   curl -s http://derf.us/history/download.php?passwd=$HISTPASS > ~/.bash_history; 
   history -r; 
}
