#! /bin/bash

## History-db

# Variables


#aliases

# functions

function post_history { 
   LAST_COMMAND=$(history 1 | sed -e 's/^ *[0-9]* *[0-9]*-[0-9]*-[0-9]* *[0-9]*:[0-9]*:[0-9]* *- *//g'); 
   curl -d hostname="$HOSTNAME" -d command="$LAST_COMMAND" http://derf.us/history/; 
} 

function get_history {  
   if ! [ -f $HISTFILE ]; then
      HISTFILE='~/.bash_history'
   fi
   echo -n "enter password: "; 
   read -s HISTPASS; 
   history -c; 
   rm $HISTFILE; 
   curl -s http://derf.us/history/download.php?passwd=$HISTPASS > $HISTFILE; 
   history -r; 
}
