#! /usr/bin/env bash

if which kubectl &> /dev/null; then
  source <(kubectl completion bash)
  alias k=kubectl
  complete -F __start_kubectl k
fi

if which flux &> /dev/null; then
  source <(flux completion bash)
  alias f=flux
  complete -F __start_flux f
fi
