#! /usr/bin/env bash

## Pass
#if which gopass &> /dev/null; then
#	alias pass=gopass
#fi

export PASSWORD_STORE_DIR=~/src/github.com/fredsmith/password-store

function genpass () {
  PASSLEN=${1:-10};
  NUMPASS=${2:-1};
  case $3 in
    nosym)
      CHARSET='a-zA-Z0-9';
      ;;
    *)
      CHARSET='a-zA-Z0-9!@#$%^&*()';
      ;;
  esac

  cat /dev/urandom | tr -dc $CHARSET | fold -w $PASSLEN | head -n $NUMPASS
}

