#! /usr/bin/env bash

# init rbenv
if which rbenv &> /dev/null; then
  eval "$(rbenv init -)"
fi

# includes
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

#variables
if [ -d $HOME/.rbenv/bin ]; then
  export PATH="$HOME/.rbenv/bin:$PATH"
fi

#aliases

if which bundle &> /dev/null; then
  alias rake="bundle exec rake"
fi
