#! /bin/bash

# init rbenv
eval "$(rbenv init -)"

# includes
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

#variables
export PATH="$HOME/.rbenv/bin:$PATH"

#aliases

alias rake="bundle exec rake"
