#! /bin/bash

# init rbenv
if which rbenv &> /dev/null; then
  eval "$(rbenv init -)"
fi

# includes
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*

#variables
export PATH="$HOME/.rbenv/bin:$PATH"

#aliases

if which bundle &> /dev/null; then
  alias rake="bundle exec rake"
fi
