#! /usr/bin/env bash


if which pass &> /dev/null; then

  #functions
  function setenv {
    source <(pass env/$1)
    echo "Env set to $1"
  }
  complete -W "$(pass ls env/ | awk '{print $2}')" setenv

  function securerun {
    scriptname=$1
    shift
    pass bin/$scriptname | bash /dev/stdin $@
  }
  complete -W "$(pass ls bin/ | awk '{print $2}')" securerun

  for util in $(pass ls bin/ | awk '{print $2}'); do
    alias $util="securerun $util"
  done

fi

