#! /usr/bin/env bash


if which pass &> /dev/null; then

  #functions
  function setenv {
    source <(pass env/$1)
    echo "Env set to $1"
    export SETENV_NAME=$1
  }
  complete -W "$(pass ls env/ | awk '{print $2}')" setenv

  function securerun {
    scriptname=$1
    shift
    pass bin/$scriptname | bash /dev/stdin $@
  }
  complete -W "$(pass ls bin/ | awk '{print $2}')" securerun

  for util in $(pass ls bin/ | awk '{print $2}'); do
    alias $util="securerun $util"
  done

  setenv_prompt() {
    if ! [ -z "$SETENV_NAME" ]; then
      echo -n "$blue[E:$green$SETENV_NAME$default]-"
    fi
  }
  export PROMPT_PLUGINS="setenv_prompt $PROMPT_PLUGINS"


fi

