#! /usr/bin/env bash


function func_sge {
      case "$1" in
         s)  
            showstat2
            ;;  
         enabled)  
            #showenabled
            qstat -f | grep "BIP" | grep -v 'd$'
            ;;  
         disabled)  
            #showdisabled
            qstat -f | grep "BIP" | grep 'd$'
            ;;
         rescheduledisabled)  
            sge disabled | print 1 | cut -f 2 -d '@' | cut -f 1 -d '.' | sge reschedule
            ;;
         explainerrors)
            for QUEUE in `sge errors`; do
               qstat -f -explain E -q \*@$QUEUE
            done
            ;;
         down)
            #shownodes | grep DOWN
            qstat -f -explain a | grep -e 'au$' -e 'auE' | print 1 | cut -f 2 -d '@' | cut -f 1 -d '.'
            ;;
         errors)
            #shownodes | grep DOWN
            #qstat -f -explain a | grep -e 'au$' -e 'auE' | print 1 | cut -f 2 -d '@' | cut -f 1 -d '.'
            qstat -f | grep 'E$' | print 1 | cut -f 2 -d '@' | cut -f 1 -d '.'
            ;;
         whatson)
            if [ "$2" == "" ]; then
               qstat -u \* | grep $HOSTNAME
            else
               qstat -u \* | grep $2
            fi
            ;;
         notok)
            shownodes | grep -v OK
            ;;
         alarm)  
            showalarm
            ;;  
         waiting)  
            showwaiting
            ;;  
         waitingusers)  
            showwaiting | print 6 | sort | uniq -c | sort -rn | head
            ;;  
         idle)
            qstat -qs d -f | grep "BIP" | grep ' 0/0' | print 1 | cut -f 2 -d '@' | cut -f 1 -d '.'
            ;;
         disable)
            while read LINE; do
               if echo $LINE | grep "@"; then
                  qmod -d $LINE; 
               else
                  qmod -d \*@$LINE;
              fi
            done
            ;;
         reschedule)
            while read LINE; do
               if echo $LINE | grep "@"; then
                  qmod -rq $LINE; 
               else
                  qmod -rq \*@$LINE;
              fi
            done
            ;;
         clearerrors)
            while read LINE; do
               qmod -cq \*@$LINE; 
            done
            ;;
         clearallerrors)
            sge errors | print 1 | sge clearerrors
            ;;
         enable)
            while read LINE; do
               if echo $LINE | grep "@"; then
                  qmod -e $LINE; 
               else
                  qmod -e \*@$LINE;
              fi
            done
            ;;
         *)  
            echo "usage:
            sge s                       show sge statistics
            sge enabled                 show enabled queues
            sge disabled                show disabled queues
            sge rescheduledisabled      reschedule all jobs on disabled queues
            sge idle                    show idle (quiesed) nodes
            sge down                    show down nodes
            sge whatson <hostname>      show which jobs are running on a host
                                        (default localhost)
            sge explainerrors           list all error state causes
            sge alarm                   show alarm status
            sge waiting                 show current waiting jobs
            sge waitingusers            show top 10 waiting users
            sge disable                 read queues from stdin and disable
            sge reschedule              read queues from stdin and reschedule all jobs
            sge enable                  read queues from stdin and enable
            sge clearerrors             read queues from stdin and clear errors
            sge clearallerrors          clear all error states from all queues
            ";
            ;;  
      esac



}

function sge {

   func_sge $@

}
