#! /bin/bash
## super-prompt
#

#variables

DEFAULTPROMPT="super-single"

#functions


prompt () {
   [[ $# = 1 ]] && mode="$1" || mode=$DEFAULTPROMPT

   case "$mode" in
   none)
      export PROMPT_COMMAND='prompt none; history -a';
      export PS1="\\\$ "
      ;;
   basicoffline)
      export PROMPT_COMMAND='prompt basicoffline; history -a';
      PS1="[\u@$hostcolor\h$default [$red""OFFLINE$default] \w]\\\$ ";
      ;;
   basic)
      export PROMPT_COMMAND='prompt basic; post_history; history -a';
      PS1="[\u@$hostcolor\h$default \w]\\\$ ";
      portcheck derf.us 80 &> /dev/null || prompt basicoffline
      ;;
   offline-single)
      export PROMPT_COMMAND='prompt offline; history -a';
      TODO=$(todo_prompt)
      GITPROMPT=$(git_prompt);
      ONLINEPROMPT="$bold$blue[$default$red""OFFLINE$bold$blue]-"
      #running this after every command is pretty expensive.  cache it maybe?
      PS1="$bold$blue[$default$blue\u@$hostcolor\h$bold$blue]$GITPROMPT$ONLINEPROMPT$bold$blue[$default$blue\t$bold]-[$default$blue\w$bold$blue] \\\$ $default"
      ;;
   super-single)
      export PROMPT_COMMAND='prompt super; post_history; history -a';
      #TODO=$(todo_prompt 2> /dev/null)
      GITPROMPT=$(git_prompt 2> /dev/null);
      ONLINEPROMPT=""
      #running this after every command is pretty expensive.  cache it maybe?
      PS1="$bold$blue[$default$blue\u@$hostcolor\h$bold$blue]$GITPROMPT$ONLINEPROMPT$bold$blue[$default$blue\t$bold]-[$default$blue\w$bold$blue] \\\$ $default"
      portcheck derf.us 80 &> /dev/null || prompt offline-single
      ;;
   offline-multi)
      export PROMPT_COMMAND='prompt offline; history -a';
      TODO=$(todo_prompt)
      GITPROMPT=$(git_prompt);
      #running this after every command is pretty expensive.  cache it maybe?
      PS1="$bold$blue┌[$default$blue\u@$hostcolor\h$bold$blue]$TODO$GITPROMPT$bold$blue[$default$red""OFFLINE$bold$blue]-[$default$blue\t \d$bold]\n$default$bold$blue└[$default$blue\w$bold$blue] \\\$ $default"
      ;;
   super-multi)
      export PROMPT_COMMAND='prompt super; post_history; history -a';
      TODO=$(todo_prompt 2> /dev/null)
      GITPROMPT=$(git_prompt 2> /dev/null);
      #running this after every command is pretty expensive.  cache it maybe?
      PS1="$bold$blue┌[$default$blue\u@$hostcolor\h$bold$blue]$TODO$GITPROMPT$bold$blue[$default$blue\t \d$bold]\n$default$bold$blue└[$default$blue\w$bold$blue] \\\$ $default"
      portcheck derf.us 80 &> /dev/null || prompt offline-multi
      ;;
   *)
      ;;
   esac
}

prompt $DEFAULTPROMPT
