#! /bin/bash

if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

if which brew &> /dev/null; then
  if [ -f `brew --prefix`/etc/bash_completion ]; then
     . `brew --prefix`/etc/bash_completion
  fi
fi
