#! /usr/bin/env bash

if [ -f /etc/bash_completion ]; then
   . /etc/bash_completion
fi

if which brew &> /dev/null; then
  if [ -d `brew --prefix`/etc/bash_completion.d ]; then
    for COMPLETIONFILE in `brew --prefix`/etc/bash_completion.d/*; do
      source $COMPLETIONFILE;
    done >/dev/null 2>&1
  fi
fi
