#! /usr/bin/env bash

export TFVER='0.15.4'

function terraform {
  docker run -i -t \
  --mount src=$(pwd)/..,target=/workspace,type=bind \
  --mount src=$(pwd),target=/workspace/project,type=bind \
  -e TF_LOG=${TF_LOG} \
  -e TF_LOG_FILE=${TF_LOG_FILE} \
  -e AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  -e AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  --workdir /workspace/project \
  hashicorp/terraform:$TFVER \
  $@
}

