#! /usr/bin/env bash

#tmux 
if [ -f $CONFIGDIR/.tmux.conf ]; then
   alias tmux="tmux -f $CONFIGDIR/.tmux.conf"
fi
if [ -f $CONFIGDIR/tmux/tmux.conf ]; then
   alias tmux="tmux -f $CONFIGDIR/tmux/tmux.conf"
fi

function settitle() {
    printf "\033]0;${1}\007"
}

function tmux_fix_ssh() {
    eval $(tmux show-env    \
        |sed -n 's/^\(SSH_[^=]*\)=\(.*\)/export \1="\2"/p')
}

alias tnew="tmux new-window"
alias tls="tmux ls"
alias tm="tmux attach -t $*"


