#! /usr/bin/env bash

#tmux 
if [ -f $CONFIGDIR/.tmux.conf ]; then
   alias tmux="tmux -f $CONFIGDIR/.tmux.conf"
fi
if [ -f $CONFIGDIR/tmux/tmux.conf ]; then
   alias tmux="tmux -f $CONFIGDIR/tmux/tmux.conf"
fi

function settitle() {
    printf "\033]0;${1}\007"
}

alias tnew="tmux new-window"
alias tls="tmux ls"
alias tm="tmux attach -t $*"


