#! /bin/bash

###todo.txt
function todo_get_location {
   hostname -f | grep nuance > /dev/null && echo "@work" ||
   echo "@home"

}

# variables
export TODOTXT_DEFAULT_ACTION=pv
export TODOTXT_AUTO_ARCHIVE=1
export TODOTXT_CFG_FILE=$HOME/Documents/Notes/todo.cfg
export TODO_LOCATION=$(todo_get_location);

# aliases 

alias t="$HOME/bin/todo.sh"
alias yesterday='t lsa | grep `date "+%Y-%m-%d" --date="yesterday"`'


## Functions

function today {
   if [ $# -gt 0 ]; then
      t add "(A) $@ $TODO_LOCATION";
   else
      t lsp A $TODO_LOCATION
   fi
}

function tomorrow {
   if [ $# -gt 0 ]; then
      t add "(B) $@ $TODO_LOCATION";
   else
      t lsp B $TODO_LOCATION
   fi
}

# prompt
function todo_prompt {

   TODO="";
   if which todo.sh &> /dev/null; then
      TODOTODAYCOUNT=$(t lsp A $TODO_LOCATION | wc -l)
      TODOTODAYCOUNT=$(($TODOTODAYCOUNT - 2));
      TODOTOMORROWCOUNT=$(t lsp B $TODO_LOCATION | wc -l)
      TODOTOMORROWCOUNT=$(($TODOTOMORROWCOUNT - 2));
      TODO="-[\[\e[0;34m\]T:\[\033[1;33m\]$TODOTODAYCOUNT\[\e[1;34m\]:\[\033[1;32m\]$TODOTOMORROWCOUNT\[\e[1;34m\]]-"
   fi
  echo "$TODO";
}


function todo_edit {
   source $TODOTXT_CFG_FILE;
   $EDITOR $TODO_DIR/todo.txt
}

function todo_replace_all_priorities {
   t -p lsp $1 $TODO_LOCATION | grep -v '\-\-' | grep -v 'TODO' | print 1 | 
   while read TASK; do 
      t pri $TASK $2; 
   done
}

function todo_done_with_today {
   todo_replace_all_priorities B A
   todo_replace_all_priorities C B
   todo_replace_all_priorities D C
   todo_replace_all_priorities E D
}
function todo_home {
   export TODO_LOCATION='@home';
}

function todo_work {
   export TODO_LOCATION='@work';
}
