#! /usr/bin/env bash

## VIM
export EDITOR='vim'
if [ -f $CONFIGDIR/vim/vimrc ]; then
  if [ ! -f $HOME/.vimrc ]; then
    ln -s $CONFIGDIR/vim/vimrc $HOME/.vimrc;
  fi
fi
if ! which vim &> /dev/null; then
	alias vim=vi
   export EDITOR=vi
fi

