#! /usr/bin/env bash

# init virtualenvwrapper
export PATH=$PATH:/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/bin/

if which virtualenvwrapper.sh &> /dev/null; then
  export WORKON_HOME="$HOME/.virtualenvs"
  export VIRTUALENVWRAPPER_PROJECT_FILENAME="working"
  export VIRTUALENVWRAPPER_HOOK_DIR="$CONFIGDIR/virtualenv"
  source `which virtualenvwrapper.sh`
fi
export PROJECT_HOME="$HOME/workspace"

virtualenv_prompt() {
  if ! [ -z "$VIRTUAL_ENV" ]; then
    echo -n "[VE:$(basename $VIRTUAL_ENV)]-";
    #settitle $(basename $VIRTUAL_ENV);
  fi
}   


export PROMPT_PLUGINS="virtualenv_prompt $PROMPT_PLUGINS";

complete -o default -o nospace -F _virtualenvs w
alias de='deactivate'
