#! /bin/bash

# init virtualenvwrapper
if [[ -s /usr/local/bin/virtualenvwrapper.sh ]]; then
  export WORKON_HOME="$HOME/.virtualenvs"
  export VIRTUALENVWRAPPER_PROJECT_FILENAME="working"
  export VIRTUALENVWRAPPER_HOOK_DIR="$CONFIGDIR/virtualenv"
  source /usr/local/bin/virtualenvwrapper.sh
fi
export PROJECT_HOME="$HOME/workspace"

virtualenv_prompt() {
  if ! [ -z "$VIRTUAL_ENV" ]; then
    echo -n "[VE:$(basename $VIRTUAL_ENV)]-";
    settitle $(basename $VIRTUAL_ENV);
  fi
}   


export PROMPT_PLUGINS="virtualenv_prompt $PROMPT_PLUGINS";

alias w='workon'
complete -o default -o nospace -F _virtualenvs w
alias de='deactivate'
