#! /bin/bash

# init virtualenvwrapper
if [[ -s /usr/local/bin/virtualenvwrapper.sh ]]; then
  export WORKON_HOME=$HOME/.virtualenvs
  source /usr/local/bin/virtualenvwrapper.sh
fi

virtualenv_prompt() {
  if ! [ -z "$VIRTUAL_ENV" ]; then
    echo -n "[VE:$(basename $VIRTUAL_ENV)]-";
  fi
}   


export PROMPT_PLUGINS="virtualenv_prompt $PROMPT_PLUGINS";
