#! /bin/bash


function func_xcat {
      case "$1" in
         lsnode)
            if [ "$2" == "" ]; then
               ssh -q xcat.infra.us.grid.nuance.com ""
            else
               USERNAME=$2;
               ssh -q xcat.infra.us.grid.nuance.com "/opt/mam/bin/gbalance -u $USERNAME --show Name,Allocated,Available"
            fi
            ;;
         *)  
            echo "usage:
            xcat lsnode <username>      show nodes by user
            xcat adduser <username>     add a user
            ";
            ;;  
      esac



}

function xcat {

   func_xcat $@

}
